### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by gz-c** [skycoin/cx-website#5]
Needs Dockerfile; mind that the repl should be a separate service.  The REPL dockerfile may belong in https://github.com/skycoin/cx

**Comment by gz-c** [comment]
@olemis wait for develop branch to be updated with latest code; major changes are coming

**Comment by mahansky** [comment]
develop updated

**Comment by iketheadore** [comment]
Is the Dockerfile ready?

**Comment by olemis** [comment]
actually , for some reason did not see this issue in my TODO list , sorry ...
